SUPER_CONFIG_PATH: ./configs/r50_deformable_detr_motip_dancetrack.yaml

# Motion-specific settings
MOTION_DIM: 32
MOTION_WEIGHT: 0.5
ASSIGNMENT_PROTOCOL: motion-guided

# Training settings for motion prediction
MOTION_LOSS_WEIGHT: 1.0
MOTION_L1_WEIGHT: 5.0
MOTION_GIOU_WEIGHT: 2.0

# Enhanced modeling
FFN_DIM_RATIO: 4  # Increased from 2 for better motion modeling